### ISSUE TITLE
support custom `shell`, or hack support for setup-miniconda?

### ISSUE THREAD

**Issue by tlambert03** [aganders3/headless-gui#4]
hey @aganders3 

One challenge that always popped up with `setup-xvfb` is that of trying to use `conda-incubator/setup-miniconda` to install certain dependencies.  (e.g. if you can't use all pip for some reason).

When using https://github.com/conda-incubator/setup-miniconda/ ... one generally has to use `shell: bash -el {0}` when running a command to access the conda environment.  This appears to be hard to do with `@actions/exec.exec`.  To demonstrate the problem:

```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}  # for setup-miniconda
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          channel-priority: strict
          python-version: '3.10'
      - name: Print python
        run: which python  # prints: /usr/share/miniconda/envs/test/bin/python 

      - name: Print from headless-gui
        uses: aganders3/headless-gui@v1
        with:
          run: which python  # prints /usr/bin/python
```

... so basically one can't access the miniconda environment from within the headless-gui context.

This is likely a shortcoming of https://github.com/actions/toolkit/tree/main/packages/exec (see https://github.com/actions/toolkit/issues/229 ...), but curious if you have any thoughts on a workaround?
